# Generated by Django 3.2.12 on 2022-02-22 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
