# Generated by Django 3.2.12 on 2022-02-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
