# Generated by Django 3.2.12 on 2022-02-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20220223_1018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
