# Generated by Django 3.2.12 on 2022-02-24 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('searched_titles', models.CharField(max_length=100)),
                ('searched_topics', models.CharField(max_length=100)),
                ('number_found_articles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Article_search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.information')),
                ('search_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.search')),
            ],
        ),
    ]
