# Generated by Django 4.0.2 on 2022-02-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('title', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=1000)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('published', models.CharField(max_length=100)),
            ],
        ),
    ]
